# no "add" here

[default]
bias_exponent_bias = 7
bias_exponent_width = 4
bias_width = 8
data_in_exponent_bias = 7
data_in_exponent_width = 4
data_in_width = 8
name = "minifloat_denorm"
weight_exponent_bias = 7
weight_exponent_width = 4
weight_width = 8

[module_classes_to_modify.conv1d]
name = "default"

[module_classes_to_modify.conv2d]
name = "default"

[module_classes_to_modify.linear]
name = "default"

[module_classes_to_modify.relu]
name = "default"

[function_classes_to_modify.bmm]
name = "default"

[function_classes_to_modify.matmul]
name = "default"

[function_classes_to_modify.relu]
name = "default"

[method_classes_to_modify.bmm]
name = "default"

[method_classes_to_modify.matmul]
name = "default"

[method_classes_to_modify.relu]
name = "default"
