# basics
model = "cnv"
dataset = "cifar10"
# training
training_optimizer = "adam"
learning_rate = 0.01
max_epochs = 10
batch_size = 32
# torch lightning
task = "classification"
num_workers = 0
num_devices = 1
accelerator = "gpu"
project_dir = "../mase_output"
