
[passes.quantize]
by = "name"
report = true

[passes.quantize.default.config]
name = "NA"


[passes.quantize.seq_blocks_0.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = false
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1

[passes.quantize.seq_blocks_2.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1

[passes.quantize.seq_blocks_5.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1


[passes.quantize.seq_blocks_7.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1


[passes.quantize.seq_blocks_10.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1


[passes.quantize.seq_blocks_12.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1


[passes.quantize.seq_blocks_1_0.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1

[passes.quantize.seq_blocks_1_2.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1


[passes.quantize.seq_blocks_1_4.config]
name = "binary_residual"
binary_training = true
data_in_residual_sign = true
data_in_levels = 2
data_in_width = 32
data_in_frac_width = 16
data_in_stochastic = 0
data_in_bipolar = 1

weight_width = 1 # does not matter
weight_stochastic = 0
weight_bipolar = 1

bias_width = 32
bias_stochastic = 0
bias_bipolar = 1