# basics
model = "jsc-s"
dataset = "jsc"
# training
training_optimizer = "adamw"
weight_decay = 1e-3
learning_rate = 1e-3
max_epochs = 1000
batch_size = 1024
# torch lightning
task = "classification"
num_workers = 0
num_devices = 1
accelerator = "cpu"
project_dir = "../mase_output"
